console.time('check your code run time')
console.log('javascript learner')
console.log(34*5)
console.log(89/7)
console.log(['javascript learner'])
console.log([1,2,4,56,7,8,9])
console.table([12,43,54,34,76,97,35])
console.log(true)
// console.warn('creating a object use warn for warning')
console.log({name: 'kaushal', age : 21, branch : 'computer'})
// console.clear()
console.timeEnd('check your code run time')
console.log('assert is used to check your condition')
// console.assert(200<104, 'age > 104 this is not possible')
// console.error('i am throwing error')
